apiVersion: batch/v1
kind: CronJob
metadata:
  name: demoqa-playwright-cron
spec:
  schedule: "0 4 * * *" # daily at 04:00 UTC (modify as needed)
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: demoqa-tests
              image: ghcr.io/ravigitgit/demoqa:latest
              imagePullPolicy: Always
              env:
                - name: DEMOQA_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: demoqa-secret
                      key: DEMOQA_BASE_URL
                - name: DEMOQA_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: demoqa-secret
                      key: DEMOQA_USERNAME
                - name: DEMOQA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: demoqa-secret
                      key: DEMOQA_PASSWORD
              volumeMounts:
                - name: artifacts
                  mountPath: /app/test-results
              command: ["npx"]
              args: ["playwright", "test", "--reporter=html,line", "--output=/app/test-results"]
          volumes:
            - name: artifacts
              emptyDir: {}
