apiVersion: v1
kind: Secret
metadata:
  name: demoqa-secret
type: Opaque
data:
  base_url: aHR0cHM6Ly9kZW1vcWEuY29t        # replace with your BASE_URL base64
  username: UmF2aVRpd2FyaQ==                # replace with your USERNAME base64
  password: UGFzc0AxMjM=                    # replace with your PASSWORD base64
